/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NflRouteImport } from './routes/nfl'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as IndexRouteImport } from './routes/index'

const NflRoute = NflRouteImport.update({
  id: '/nfl',
  path: '/nfl',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/nfl': typeof NflRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/nfl': typeof NflRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/nfl': typeof NflRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leaderboards' | '/nfl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leaderboards' | '/nfl'
  id: '__root__' | '/' | '/leaderboards' | '/nfl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  NflRoute: typeof NflRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nfl': {
      id: '/nfl'
      path: '/nfl'
      fullPath: '/nfl'
      preLoaderRoute: typeof NflRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  NflRoute: NflRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
