/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNflDatasetsRouteImport } from './routes/api/nfl/datasets'
import { Route as ApiNflDatasetsDatasetIdSchemaRouteImport } from './routes/api/nfl/datasets.$datasetId.schema'
import { Route as ApiNflDatasetsDatasetIdDataRouteImport } from './routes/api/nfl/datasets.$datasetId.data'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNflDatasetsRoute = ApiNflDatasetsRouteImport.update({
  id: '/api/nfl/datasets',
  path: '/api/nfl/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNflDatasetsDatasetIdSchemaRoute =
  ApiNflDatasetsDatasetIdSchemaRouteImport.update({
    id: '/$datasetId/schema',
    path: '/$datasetId/schema',
    getParentRoute: () => ApiNflDatasetsRoute,
  } as any)
const ApiNflDatasetsDatasetIdDataRoute =
  ApiNflDatasetsDatasetIdDataRouteImport.update({
    id: '/$datasetId/data',
    path: '/$datasetId/data',
    getParentRoute: () => ApiNflDatasetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/api/nfl/datasets': typeof ApiNflDatasetsRouteWithChildren
  '/api/nfl/datasets/$datasetId/data': typeof ApiNflDatasetsDatasetIdDataRoute
  '/api/nfl/datasets/$datasetId/schema': typeof ApiNflDatasetsDatasetIdSchemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/api/nfl/datasets': typeof ApiNflDatasetsRouteWithChildren
  '/api/nfl/datasets/$datasetId/data': typeof ApiNflDatasetsDatasetIdDataRoute
  '/api/nfl/datasets/$datasetId/schema': typeof ApiNflDatasetsDatasetIdSchemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/api/nfl/datasets': typeof ApiNflDatasetsRouteWithChildren
  '/api/nfl/datasets/$datasetId/data': typeof ApiNflDatasetsDatasetIdDataRoute
  '/api/nfl/datasets/$datasetId/schema': typeof ApiNflDatasetsDatasetIdSchemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/api/nfl/datasets'
    | '/api/nfl/datasets/$datasetId/data'
    | '/api/nfl/datasets/$datasetId/schema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/api/nfl/datasets'
    | '/api/nfl/datasets/$datasetId/data'
    | '/api/nfl/datasets/$datasetId/schema'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/api/nfl/datasets'
    | '/api/nfl/datasets/$datasetId/data'
    | '/api/nfl/datasets/$datasetId/schema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  ApiNflDatasetsRoute: typeof ApiNflDatasetsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nfl/datasets': {
      id: '/api/nfl/datasets'
      path: '/api/nfl/datasets'
      fullPath: '/api/nfl/datasets'
      preLoaderRoute: typeof ApiNflDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nfl/datasets/$datasetId/schema': {
      id: '/api/nfl/datasets/$datasetId/schema'
      path: '/$datasetId/schema'
      fullPath: '/api/nfl/datasets/$datasetId/schema'
      preLoaderRoute: typeof ApiNflDatasetsDatasetIdSchemaRouteImport
      parentRoute: typeof ApiNflDatasetsRoute
    }
    '/api/nfl/datasets/$datasetId/data': {
      id: '/api/nfl/datasets/$datasetId/data'
      path: '/$datasetId/data'
      fullPath: '/api/nfl/datasets/$datasetId/data'
      preLoaderRoute: typeof ApiNflDatasetsDatasetIdDataRouteImport
      parentRoute: typeof ApiNflDatasetsRoute
    }
  }
}

interface ApiNflDatasetsRouteChildren {
  ApiNflDatasetsDatasetIdDataRoute: typeof ApiNflDatasetsDatasetIdDataRoute
  ApiNflDatasetsDatasetIdSchemaRoute: typeof ApiNflDatasetsDatasetIdSchemaRoute
}

const ApiNflDatasetsRouteChildren: ApiNflDatasetsRouteChildren = {
  ApiNflDatasetsDatasetIdDataRoute: ApiNflDatasetsDatasetIdDataRoute,
  ApiNflDatasetsDatasetIdSchemaRoute: ApiNflDatasetsDatasetIdSchemaRoute,
}

const ApiNflDatasetsRouteWithChildren = ApiNflDatasetsRoute._addFileChildren(
  ApiNflDatasetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  ApiNflDatasetsRoute: ApiNflDatasetsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
